// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(SavingsPoolContext))]
    [Migration("20260525075611_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.PoolContributors", b =>
                {
                    b.Property<int>("ContributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContributorId"));

                    b.Property<int?>("SavingsPoolsId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusContributionStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("ContributorId");

                    b.HasIndex("SavingsPoolsId");

                    b.HasIndex("StatusContributionStatusId");

                    b.ToTable("PoolContributor");
                });

            modelBuilder.Entity("Backend.Models.SavingsPool", b =>
                {
                    b.Property<int>("SavingsPoolsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavingsPoolsId"));

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("integer");

                    b.Property<int>("SchedTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("integer");

                    b.HasKey("SavingsPoolsId");

                    b.HasIndex("SchedTypeId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("SavingsPool");
                });

            modelBuilder.Entity("Backend.Models.SchedTypes", b =>
                {
                    b.Property<int>("SchedTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchedTypeId"));

                    b.Property<string>("SchedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SchedTypeId");

                    b.ToTable("SchedType");
                });

            modelBuilder.Entity("Backend.Models.StatusContribution", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("StatusContribution");
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PoolContributorsContributorId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("PoolContributorsContributorId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Backend.Models.PoolContributors", b =>
                {
                    b.HasOne("Backend.Models.SavingsPool", null)
                        .WithMany("Contributor")
                        .HasForeignKey("SavingsPoolsId");

                    b.HasOne("Backend.Models.StatusContribution", "StatusContribution")
                        .WithMany("PoolContributor")
                        .HasForeignKey("StatusContributionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusContribution");
                });

            modelBuilder.Entity("Backend.Models.SavingsPool", b =>
                {
                    b.HasOne("Backend.Models.SchedTypes", "SchedType")
                        .WithMany()
                        .HasForeignKey("SchedTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Users", null)
                        .WithMany("SavingsPools")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("SchedType");
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.HasOne("Backend.Models.PoolContributors", null)
                        .WithMany("User")
                        .HasForeignKey("PoolContributorsContributorId");
                });

            modelBuilder.Entity("Backend.Models.PoolContributors", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.SavingsPool", b =>
                {
                    b.Navigation("Contributor");
                });

            modelBuilder.Entity("Backend.Models.StatusContribution", b =>
                {
                    b.Navigation("PoolContributor");
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.Navigation("SavingsPools");
                });
#pragma warning restore 612, 618
        }
    }
}
