// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(SavingsPoolContext))]
    [Migration("20260526055627_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.PoolContributors", b =>
                {
                    b.Property<int>("ContributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContributorId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ContributionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SavingsPoolId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ContributorId");

                    b.HasIndex("SavingsPoolId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("PoolContributors");

                    b.HasData(
                        new
                        {
                            ContributorId = 1,
                            Amount = 500,
                            ContributionDate = new DateTime(2026, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 1,
                            StatusId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ContributorId = 2,
                            Amount = 500,
                            ContributionDate = new DateTime(2026, 1, 16, 14, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 1,
                            StatusId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ContributorId = 3,
                            Amount = 500,
                            ContributionDate = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 1,
                            StatusId = 1,
                            UserId = 3
                        },
                        new
                        {
                            ContributorId = 4,
                            Amount = 500,
                            ContributionDate = new DateTime(2026, 1, 18, 16, 45, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 1,
                            StatusId = 2,
                            UserId = 4
                        },
                        new
                        {
                            ContributorId = 5,
                            Amount = 500,
                            ContributionDate = new DateTime(2026, 1, 19, 11, 20, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 1,
                            StatusId = 2,
                            UserId = 5
                        },
                        new
                        {
                            ContributorId = 6,
                            Amount = 300,
                            ContributionDate = new DateTime(2026, 2, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 2,
                            StatusId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ContributorId = 7,
                            Amount = 300,
                            ContributionDate = new DateTime(2026, 2, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 2,
                            StatusId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ContributorId = 8,
                            Amount = 300,
                            ContributionDate = new DateTime(2026, 2, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 2,
                            StatusId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ContributorId = 9,
                            Amount = 300,
                            ContributionDate = new DateTime(2026, 2, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 2,
                            StatusId = 1,
                            UserId = 4
                        },
                        new
                        {
                            ContributorId = 10,
                            Amount = 1500,
                            ContributionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 3,
                            StatusId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ContributorId = 11,
                            Amount = 1500,
                            ContributionDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 3,
                            StatusId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ContributorId = 12,
                            Amount = 1500,
                            ContributionDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 3,
                            StatusId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ContributorId = 13,
                            Amount = 200,
                            ContributionDate = new DateTime(2026, 5, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 4,
                            StatusId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ContributorId = 14,
                            Amount = 200,
                            ContributionDate = new DateTime(2026, 5, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 4,
                            StatusId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ContributorId = 15,
                            Amount = 200,
                            ContributionDate = new DateTime(2026, 5, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 4,
                            StatusId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ContributorId = 16,
                            Amount = 200,
                            ContributionDate = new DateTime(2026, 5, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 4,
                            StatusId = 2,
                            UserId = 4
                        },
                        new
                        {
                            ContributorId = 17,
                            Amount = 2000,
                            ContributionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 5,
                            StatusId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ContributorId = 18,
                            Amount = 2000,
                            ContributionDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 5,
                            StatusId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ContributorId = 19,
                            Amount = 2000,
                            ContributionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SavingsPoolId = 5,
                            StatusId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Backend.Models.SavingsPool", b =>
                {
                    b.Property<int>("SavingsPoolsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavingsPoolsId"));

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("integer");

                    b.Property<int>("SchedTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SavingsPoolsId");

                    b.HasIndex("SchedTypeId");

                    b.ToTable("SavingsPools");

                    b.HasData(
                        new
                        {
                            SavingsPoolsId = 1,
                            CurrentAmount = 2500,
                            SchedTypeId = 4,
                            TargetAmount = 5000,
                            Title = "Summer Vacation Fund"
                        },
                        new
                        {
                            SavingsPoolsId = 2,
                            CurrentAmount = 1200,
                            SchedTypeId = 2,
                            TargetAmount = 3000,
                            Title = "New Laptop Group Buy"
                        },
                        new
                        {
                            SavingsPoolsId = 3,
                            CurrentAmount = 4500,
                            SchedTypeId = 4,
                            TargetAmount = 10000,
                            Title = "Emergency Rainy Day Fund"
                        },
                        new
                        {
                            SavingsPoolsId = 4,
                            CurrentAmount = 800,
                            SchedTypeId = 1,
                            TargetAmount = 800,
                            Title = "Office Party Budget"
                        },
                        new
                        {
                            SavingsPoolsId = 5,
                            CurrentAmount = 6000,
                            SchedTypeId = 5,
                            TargetAmount = 15000,
                            Title = "Quarterly Investment Pool"
                        });
                });

            modelBuilder.Entity("Backend.Models.SchedTypes", b =>
                {
                    b.Property<int>("SchedTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchedTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SchedTypeId");

                    b.ToTable("SchedTypes");

                    b.HasData(
                        new
                        {
                            SchedTypeId = 1,
                            Name = "Daily"
                        },
                        new
                        {
                            SchedTypeId = 2,
                            Name = "Weekly"
                        },
                        new
                        {
                            SchedTypeId = 3,
                            Name = "Bi-Weekly"
                        },
                        new
                        {
                            SchedTypeId = 4,
                            Name = "Monthly"
                        },
                        new
                        {
                            SchedTypeId = 5,
                            Name = "Quarterly"
                        },
                        new
                        {
                            SchedTypeId = 6,
                            Name = "Yearly"
                        });
                });

            modelBuilder.Entity("Backend.Models.StatusContribution", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("StatusContributions");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusName = "Failed"
                        },
                        new
                        {
                            StatusId = 4,
                            StatusName = "Refunded"
                        });
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Bob Smith"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Charlie Brown"
                        },
                        new
                        {
                            UserId = 4,
                            Name = "Diana Prince"
                        },
                        new
                        {
                            UserId = 5,
                            Name = "Evan Wright"
                        });
                });

            modelBuilder.Entity("Backend.Models.PoolContributors", b =>
                {
                    b.HasOne("Backend.Models.SavingsPool", "SavingsPool")
                        .WithMany("Contributors")
                        .HasForeignKey("SavingsPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.StatusContribution", "StatusContribution")
                        .WithMany("PoolContributors")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Users", "User")
                        .WithMany("PoolContributors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SavingsPool");

                    b.Navigation("StatusContribution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.SavingsPool", b =>
                {
                    b.HasOne("Backend.Models.SchedTypes", "SchedType")
                        .WithMany("SavingsPools")
                        .HasForeignKey("SchedTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchedType");
                });

            modelBuilder.Entity("Backend.Models.SavingsPool", b =>
                {
                    b.Navigation("Contributors");
                });

            modelBuilder.Entity("Backend.Models.SchedTypes", b =>
                {
                    b.Navigation("SavingsPools");
                });

            modelBuilder.Entity("Backend.Models.StatusContribution", b =>
                {
                    b.Navigation("PoolContributors");
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.Navigation("PoolContributors");
                });
#pragma warning restore 612, 618
        }
    }
}
